env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  # Suppress errors for missing 'import React' in files (Vite imports React globally at build-time) (0 = off)
  react/react-in-jsx-scope: 0

  # Make sure TSX files register as React.
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .jsx
        - .tsx
